###
# Date        : 2020-10-30 10:32:39
# Author      : shy
# Email       : yushuibo@ebupt.com / hengchen2005@gmail.com
# Version     : v1.0
# Description : -
###

data:
  env: config-single-client-dev
  user:
    username: single-client-user
    password: 12345678
