###
# Date        : 2020-10-30 10:39:58
# Author      : shy
# Email       : yushuibo@ebupt.com / hengchen2005@gmail.com
# Version     : v1.0
# Description : -
###

data:
  env: config-eureka-client-prod
  user:
    username: eureka-client-user
    password: abc@123456
