###
# Date        : 2020-10-30 10:34:01
# Author      : shy
# Email       : yushuibo@ebupt.com / hengchen2005@gmail.com
# Version     : v1.0
# Description : -
###

data:
  env: config-single-client-prod
  user:
    username: single-client-user
    password: abc@123456
